// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbu18y9pOEnKgJUXr0LXchvBIDWIC9kgM',
    appId: '1:254352981336:web:a2fafe5f19ba27a73ef92d',
    messagingSenderId: '254352981336',
    projectId: 'e-commerce-app-b87f6',
    authDomain: 'e-commerce-app-b87f6.firebaseapp.com',
    storageBucket: 'e-commerce-app-b87f6.appspot.com',
    measurementId: 'G-Z453YR5KNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzIACEcoQTqJftVqgAzjVhA3n681U0s4s',
    appId: '1:254352981336:android:4bc35d74cd02c94d3ef92d',
    messagingSenderId: '254352981336',
    projectId: 'e-commerce-app-b87f6',
    storageBucket: 'e-commerce-app-b87f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrczwjlgWj8BWmSJURnzZG0YMK2qZ73Zo',
    appId: '1:254352981336:ios:f9a57a806a5bc0c43ef92d',
    messagingSenderId: '254352981336',
    projectId: 'e-commerce-app-b87f6',
    storageBucket: 'e-commerce-app-b87f6.appspot.com',
    iosBundleId: 'com.example.footwearAdmin',
  );
}
